version: '3.9'

services:
  apt-proxy:
    image: webpatchers/apt-proxy:latest
    container_name: apt-proxy
    restart: unless-stopped
    ports:
      - "3142:3142"  # Apt-Cacher-NG Proxy port
    volumes:
      - apt-cache:/var/cache/apt-cacher-ng  # Cache directory
      - apt-mirror:/var/spool/apt-mirror  # Apt mirror storage
      - aptutil:/var/lib/aptutil  # Apt utility directory
    environment:
      - APT_CACHER_NG_USER=apt-cacher-ng
      - APT_CACHER_NG_CACHE_DIR=/var/cache/apt-cacher-ng
      - APT_CACHER_NG_LOG_DIR=/var/log/apt-cacher-ng
      - DEBIAN_FRONTEND=noninteractive
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3142/acng-report.html"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

volumes:
  apt-cache:
  apt-mirror:
  aptutil:

networks:
  proxy-net:
    driver: bridge
